const fallbackMiniPracticeQuestions = [
  {
    id: 1,
    subject: "English",
    question: "If I _____ enough money, I would buy a new laptop.",
    options: { A: "have", B: "had", C: "will have", D: "has" },
    answer: "B"
  },
  {
    id: 2,
    subject: "English",
    question: "Choose the synonym of 'robust'.",
    options: { A: "Weak", B: "Strong", C: "Tiny", D: "Slow" },
    answer: "B"
  },
  {
    id: 3,
    subject: "Ona tili",
    question: "Qaysi so'z imloviy jihatdan to'g'ri yozilgan?",
    options: { A: "Xoxlayman", B: "Hoxlayman", C: "Xohlayman", D: "Hohlayman" },
    answer: "C"
  }
];

function normalizeQuizQuestion(question) {
    const answerKeys = Object.keys(question.options || {});
    const options = Object.values(question.options || {});
    const answerIndex = answerKeys.indexOf(question.answer);
    return [question.question, options, answerIndex >= 0 ? answerIndex : 0];
}

let miniPracticeQuestions = [];
let miniTestQuestions = [];
window.miniTestQuestions = [];

function setMiniPracticeQuestions(questions) {
    miniPracticeQuestions = (questions || []).slice(0, 10);
    miniTestQuestions = miniPracticeQuestions.map(normalizeQuizQuestion);
    window.miniTestQuestions = miniTestQuestions;
}

async function loadMiniPracticeQuestions() {
    try {
        const response = await fetch('./dtm.json');
        if (!response.ok) throw new Error('Could not load dtm.json');
        const data = await response.json();
        const rawQuestions = Array.isArray(data?.questions) ? data.questions : [];
        setMiniPracticeQuestions(rawQuestions);
    } catch (error) {
        setMiniPracticeQuestions(fallbackMiniPracticeQuestions);
    }
}

window.loadMiniPracticeQuestions = loadMiniPracticeQuestions;
loadMiniPracticeQuestions();

const QB={
ona_tili:[
["'Kitob' so'zi qaysi turkumga mansub?",["Ot","Fe'l","Sifat","Ravish"],0],
["Qaysi so'z yasama?",["Uy","Kitobxon","Suv","Yer"],1],
["Fe'lning noaniq shakli qanday tugaydi?",["-(i)sh","-moq","-lik","-chi"],1],
["'Yaxshi' so'zining antonimi?",["Chiroyli","Yomon","Katta","Kichik"],1],
["Qo'shma gap nechta oddiy gapdan tashkil topadi?",["1 ta","2 va undan ko'p","Faqat 3 ta","Faqat 4 ta"],1],
["Ega qaysi so'z bilan ifodalanadi?",["Fe'l","Ot","Sifat","Ravish"],1],
["To'ldiruvchi qaysi savollarga javob bo'ladi?",["Kim? Nima?","Qanday?","Qachon?","Qayerda?"],0],
["Qaysi gap sodda gap?",["Men kitob o'qidim.","Men keldim va u ketdi.","Quyosh chiqdi, qushlar sayray boshladi.","U keldi, lekin men ketdim."],0],
["Undov so'ziga misol?",["Voh!","Va","Lekin","Chunki"],0],
["Qaysi qatorda faqat sifatlar berilgan?",["chiroyli, baland, katta","tez, sekin, yugurdi","kitob, daftar, ruchka","o'qidi, yozdi, chizdi"],0]
],
matematika:[
["3x - 7 = 14 tenglamaning yechimi?",["5","7","8","3"],1],
["√144 ning qiymati?",["11","12","13","14"],1],
["(a+b)² = ?",["a²+b²","a²+2ab+b²","a²-2ab+b²","2a+2b"],1],
["sin 30° = ?",["1","0.5","0.7","0.86"],1],
["log₂ 8 = ?",["2","3","4","8"],1],
["2, 5, 8, 11... ketma-ketlikning 10-hadi?",["27","29","31","33"],1],
["x²-5x+6=0 ildizlari yig'indisi?",["5","6","-5","1"],0],
["Doira yuzasi formulasi?",["2πr","πr²","πd","r²"],1],
["60 ning 15% i nechaga teng?",["6","9","12","15"],1],
["|x-3|=5 tenglamasining yechimlari?",["8 va -2","3 va 5","8 va 2","-8 va 2"],0]
],
tarix:[
["Amir Temur qachon tug'ilgan?",["1336","1370","1405","1300"],0],
["O'zbekiston mustaqillikka qachon erishgan?",["1990","1991","1992","1989"],1],
["O'zbekiston Konstitutsiyasi qabul qilingan yil?",["1991","1993","1992","1994"],2],
["Mustaqillik kuni qachon nishonlanadi?",["1-sentabr","8-dekabr","21-mart","9-may"],0],
["'Avesto' qaysi dinga oid kitob?",["Islom","Buddizm","Zardushtiylik","Xristianlik"],2],
["Jadidchilik harakati asoschisi kim?",["Behbudiy","Avloniy","Fitrat","Qodiriy"],0],
["Buyuk Ipak yo'li qayerlarni bog'lagan?",["Sharq-G'arb","Shimol-Janub","Yevropa-Afrika","Amerika-Osiyo"],0],
["Movarounnahr qaysi hududni anglatadi?",["Ikki daryo oralig'i","Tog' orasi","Cho'l","Dengiz bo'yi"],0],
["Birinchi Prezident kim?",["Sh.Mirziyoyev","I.Karimov","A.Aripov","E.Halimov"],1],
["Samarqand qaysi davlat poytaxti bo'lgan?",["Somoniylar","Temuriylar","Xorazmshohlar","Qoraxoniylar"],1]
],
fizika:[
["Nyutonning 2-qonuni formulasi?",["F=ma","F=mv","F=mg","F=mgh"],0],
["Yorug'lik tezligi qancha?",["3×10⁶","3×10⁸","3×10⁵","3×10¹⁰"],1],
["1 kVt necha Vattga teng?",["100","500","1000","10000"],2],
["Elektr tokining birligi?",["Volt","Amper","Om","Vatt"],1],
["Erkin tushish tezlanishi?",["9.8 m/s²","10.8 m/s²","8.9 m/s²","11 m/s²"],0],
["Issiqlik miqdori formulasi?",["Q=cm∆t","Q=mgh","Q=mv²/2","Q=Fs"],0],
["Zichlik formulasi?",["ρ=m/V","ρ=F/S","ρ=V/m","ρ=m×V"],0],
["Arximed kuchi nimaga bog'liq?",["Jism hajmi","Jism massasi","Jism rangi","Jism shakli"],0],
["Elektr qarshilik birligi?",["Amper","Volt","Om","Vatt"],2],
["Bosim formulasi?",["P=F/S","P=m/V","P=F×S","P=S/F"],0],
["Ish formulasi?",["A=Fs","A=mv","A=mgh/t","A=Pt²"],0],
["Quvvat formulasi?",["P=A/t","P=Fs","P=mv","P=mgh"],0],
["Tezlik formulasi?",["v=S/t","v=t/S","v=S×t","v=a/t"],0],
["Tezlanish formulasi?",["a=v/t","a=t/v","a=v×t","a=S/t"],0],
["Kinetik energiya formulasi?",["E=mv²/2","E=mgh","E=Fs","E=Pt"],0],
["Potensial energiya formulasi?",["E=mgh","E=mv²/2","E=Fs","E=mc²"],0],
["Om qonuni formulasi?",["I=U/R","U=IR²","R=IU","I=UR"],0],
["Chastota birligi?",["Gerts","Nyuton","Paskal","Joul"],0],
["To'lqin uzunligi formulasi?",["λ=v/f","λ=vf","λ=f/v","λ=v+f"],0],
["Magnit maydon induksiyasi birligi?",["Tesla","Amper","Volt","Vatt"],0],
["Linza formulasi 1/F = ?",["1/d+1/f","d+f","d×f","1/d-1/f"],0],
["Kondensator sig'imi birligi?",["Farad","Genri","Tesla","Om"],0],
["Termodinamikaning 1-qonuni?",["∆U=Q-A","∆U=Q+A","Q=∆U×A","A=Q×∆U"],0],
["Impuls formulasi?",["p=mv","p=ma","p=Ft²","p=mgh"],0],
["Mexanik ish birligi?",["Joul","Nyuton","Vatt","Paskal"],0],
["Ideal gaz holat tenglamasi?",["PV=nRT","PV=mRT","PT=nRV","P=nRT/m"],0],
["Kulonning qonuni formulasi?",["F=kq₁q₂/r²","F=q₁q₂r²","F=kq/r","F=q₁+q₂"],0],
["Faradeyning 1-qonuni nimaga oid?",["Elektroliz","Magnit","Yorug'lik","Tovush"],0],
["Diffuziya nima?",["Moddalar aralashishi","Suyuqlik oqishi","Gaz kengayishi","Qattiq jism siqilishi"],0],
["Konveksiya qayerda kuzatiladi?",["Suyuqlik va gazlarda","Faqat qattiq jismlarda","Vakuumda","Faqat metallarda"],0]
],
kimyo:[
["Suvning kimyoviy formulasi?",["H2O","CO2","NaCl","H2SO4"],0],
["Mendeleyev jadvalidagi 1-element?",["Geliy","Vodorod","Litiy","Uglerod"],1],
["Oshtuzdagi kislorod foizi?",["21%","78%","1%","50%"],0],
["Kislotaga misol?",["NaOH","HCl","NaCl","H2O"],1],
["pH=7 nimani bildiradi?",["Kislota","Neytral","Ishqor","Tuz"],1],
["Tuzga misol?",["NaCl","HCl","NaOH","H2O"],0],
["Oksidlanish nima?",["Elektron berish","Elektron olish","Proton berish","Neytron olish"],0],
["Valentlik nima?",["Bog' hosil qilish qobiliyati","Atom massasi","Atom radiusi","Elektron soni"],0],
["Ishqorga misol?",["HCl","NaOH","NaCl","CO2"],1],
["Mol nima?",["Modda miqdori birligi","Massa birligi","Hajm birligi","Bosim birligi"],0],
["Avogadro soni?",["6.02×10²³","3×10⁸","9.8","1.6×10⁻¹⁹"],0],
["CO2 ning nomi?",["Karbonat angidrid","Suv","Tuz kislota","Oltingugurt"],0],
["Metallarning umumiy xossasi?",["Elektr o'tkazuvchanlik","Mo'rtlik","Gazsimonlik","Rangsizlik"],0],
["Kimyoviy bog' turlari?",["Kovalent, ionli, metall","Faqat ionli","Faqat kovalent","Faqat metall"],0],
["Reaksiya tezligiga nima ta'sir qiladi?",["Harorat","Rang","Hid","Shakl"],0],
["Katalizator nima qiladi?",["Reaksiyani tezlashtiradi","Reaksiyani to'xtatadi","Moddani eritadi","Rangini o'zgartiradi"],0],
["Elektrolitik dissotsiatsiya nima?",["Ionlarga ajralish","Cho'kma tushishi","Bug'lanish","Kristallanish"],0],
["Organik kimyoning asosiy elementi?",["Uglerod","Temir","Mis","Oltin"],0],
["Metan formulasi?",["CH4","C2H6","C2H4","C6H6"],0],
["Etanol formulasi?",["C2H5OH","CH3OH","C3H7OH","C6H12O6"],0],
["Tuzlar qanday hosil bo'ladi?",["Kislota+ishqor","Suv+gaz","Metall+suv","Gaz+gaz"],0],
["Vodorodning valentligi?",["1","2","3","4"],0],
["Kislorodning valentligi?",["1","2","3","4"],1],
["Kislota oksidi misol?",["SO3","Na2O","CaO","K2O"],0],
["Ishqoriy metall?",["Natriy","Temir","Mis","Oltin"],0],
["Galogenlar guruhiga kiradi?",["Xlor","Kislorod","Azot","Uglerod"],0],
["Qaysi gaz yonishni qo'llaydi?",["Kislorod","Azot","Vodorod","Geliy"],0],
["Oqsil tarkibida qaysi element bor?",["Azot","Oltin","Kumush","Mis"],0],
["Polimer nima?",["Katta molekula","Kichik atom","Oddiy modda","Eritma"],0],
["Galvanik element nima?",["Kimyoviy tok manbai","Issiqlik manbai","Yorug'lik manbai","Tovush manbai"],0]
],
biologiya:[
["Hujayraning energiya markazi?",["Yadro","Mitoxondriya","Ribosoma","Lizosoma"],1],
["DNK qanday struktura?",["Bir zanjirli","Ikki spiralli","Uch spiralli","To'rt spiralli"],1],
["Fotosintez qayerda sodir bo'ladi?",["Mitoxondriyada","Xloroplastda","Yadroda","Ribosomada"],1],
["Odam organizmidagi xromosoma soni?",["44","46","48","23"],1],
["Qon guruhlari nechta?",["2","3","4","6"],2],
["Yurak necha kamerali?",["2","3","4","5"],2],
["Nerv tizimining asosiy organi?",["Yurak","Miya","Jigar","Buyrak"],1],
["Ovqat hazm qilish qayerdan boshlanadi?",["Oshqozon","Og'iz bo'shlig'i","Ichak","Jigar"],1],
["Gemoglobin qayerda bo'ladi?",["Eritrositda","Leykositda","Trombositda","Plazmada"],0],
["O'simlikning vegetativ organi?",["Gul","Ildiz","Meva","Urug'"],1],
["Mitoz bo'linish natijasi?",["2 ta hujayra","4 ta hujayra","8 ta hujayra","1 ta hujayra"],0],
["Meyoz natijasi?",["2 ta hujayra","4 ta hujayra","8 ta hujayra","1 ta hujayra"],1],
["Viruslar qanday ko'payadi?",["Bo'linish","Hujayra ichida","Urug'lanish","Kurtak"],1],
["Ekotizim nima?",["Tirik va notirik tabiat birligi","Faqat o'simliklar","Faqat hayvonlar","Faqat suv"],0],
["Qaysi vitamin immunitetni mustahkamlaydi?",["A","B","C","D"],2],
["Insulinni qaysi organ ishlab chiqaradi?",["Jigar","Oshqozon baqa","Buyrak","Taloq"],1],
["Fotosinezda nima ajraladi?",["Suv","Kislorod","CO2","Glyukoza"],0],
["Odam skeleti necha suyakdan iborat?",["150","206","300","180"],1],
["Qaysi organ qonni tozalaydi?",["Yurak","Buyrak","Jigar","O'pka"],1],
["Dominant belgi nima?",["Ustun belgi","Yashirin belgi","Yangi belgi","O'zgargan belgi"],0],
["Retsessiv belgi qachon namoyon bo'ladi?",["Gomozigotada","Geterozigotada","Har doim","Hech qachon"],0],
["Ekologiya nimani o'rganadi?",["Organizmlar va muhit munosabati","Hujayralar","Kasalliklar","Kimyoviy reaksiyalar"],0],
["Qaysi organizm avtotrof?",["Hayvon","O'simlik","Zamburug'","Virus"],1],
["Geterotrof organizmga misol?",["O'simlik","Hayvon","Bakteriya","Suvo'ti"],1],
["Populyatsiya nima?",["Bir tur individlari yig'indisi","Turli turlar","Biotsenoz","Ekotizim"],0],
["Biosfera kim tomonidan aniqlangan?",["Darvin","Vernadskiy","Mendel","Linney"],1],
["Tabiiy tanlanish nazariyasi muallifi?",["Lamark","Darvin","Mendel","Linney"],1],
["Gen nima?",["DNK bo'lagi","Oqsil","Hujayra","Organ"],0],
["Genotip nima?",["Genlar yig'indisi","Tashqi ko'rinish","Muhit ta'siri","Mutatsiya"],0],
["Fenotip nima?",["Tashqi ko'rinish belgilari","Genlar yig'indisi","DNK strukturasi","Xromosoma soni"],0]
],
informatika:[
["1 bayt necha bit?",["4","8","16","32"],1],
["CPU ning vazifasi?",["Ma'lumot saqlash","Hisoblash va boshqarish","Chop etish","Tarmoqqa ulanish"],1],
["RAM nima?",["Doimiy xotira","Operativ xotira","Qattiq disk","Protsessor"],1],
["HTML nima uchun ishlatiladi?",["Web sahifa yaratish","Dasturlash","Ma'lumotlar bazasi","Operatsion tizim"],0],
["Eng kichik ma'lumot birligi?",["Bayt","Bit","Kilobayt","Megabayt"],1],
["IP manzil nima?",["Kompyuter manzili tarmoqda","Dastur nomi","Fayl turi","Xotira hajmi"],0],
["Algoritm nima?",["Buyruqlar ketma-ketligi","Dasturlash tili","Kompyuter turi","Tarmoq turi"],0],
["Qaysi biri dasturlash tili?",["Windows","Python","Chrome","Word"],1],
["Operatsion tizimga misol?",["Python","Linux","HTML","MySQL"],1],
["1 KB necha bayt?",["100","512","1024","2048"],2],
["SQL nima uchun ishlatiladi?",["Web dizayn","Ma'lumotlar bazasi","Grafika","O'yinlar"],1],
["Tarmoq topologiyasi turlari?",["Yulduz, halqa, shina","Faqat yulduz","Faqat halqa","Faqat shina"],0],
["Virus nima?",["Zararli dastur","Foydali dastur","Operatsion tizim","Brauzer"],0],
["Firewall vazifasi?",["Himoya","Chop etish","Saqlash","Hisoblash"],0],
["Boolean ma'lumot turi?",["True/False","Raqam","Matn","Ro'yxat"],0],
["CSS nima uchun?",["Web sahifani bezash","Dasturlash","Ma'lumotlar bazasi","Tarmoq"],0],
["JavaScript qayerda ishlaydi?",["Brauzerda","Printerda","Skanerda","Modemda"],0],
["Git nima?",["Versiyalar boshqaruv tizimi","Dasturlash tili","Brauzer","Operatsion tizim"],0],
["Cloud computing nima?",["Bulutli hisoblash","Mahalliy server","Printer","Monitor"],0],
["Qaysi biri brauzer?",["Python","Chrome","Linux","MySQL"],1],
["Ikkilik sanoq tizimida 10 = ?",["2","4","8","16"],0],
["Rekursiya nima?",["Funksiya o'zini chaqirishi","Tsikl","O'zgaruvchi","Massiv"],0],
["OOP nima?",["Obyektga yo'naltirilgan dasturlash","Oddiy dasturlash","Ma'lumotlar bazasi","Tarmoq"],0],
["Massiv nima?",["Bir turdagi ma'lumotlar to'plami","Bitta o'zgaruvchi","Funksiya","Tsikl"],0],
["HTTP nima?",["Protokol","Dasturlash tili","Brauzer","Server"],0],
["Qaysi port HTTP uchun standart?",["21","80","443","3306"],1],
["Kompyuter arxitekturasi asoschisi?",["Fon Neyman","Nyuton","Eyler","Gauss"],0],
["Eng katta xotira birligi?",["Gigabayt","Terabayt","Megabayt","Kilobayt"],1],
["API nima?",["Dastur interfeysi","Brauzer","Server","Xotira"],0],
["Qaysi biri ma'lumotlar strukturasi?",["Stack","HTML","CSS","HTTP"],0]
],
geografiya:[
["Yer yuzasining qancha foizi suv?",["50%","71%","30%","90%"],1],
["Eng baland cho'qqi?",["K2","Everest","Elbrus","Kilimanjaro"],1],
["O'zbekiston poytaxti?",["Samarqand","Toshkent","Buxoro","Xiva"],1],
["Eng katta okean?",["Atlantika","Tinch","Hind","Shimoliy Muz"],1],
["O'zbekiston aholisi taxminan?",["25 mln","36 mln","45 mln","20 mln"],1],
["Qaysi davlat orol davlat?",["Fransiya","Yaponiya","Germaniya","Rossiya"],1],
["Sahroi Kabir qayerda?",["Osiyo","Afrika","Yevropa","Amerika"],1],
["O'zbekiston nechta viloyatdan iborat?",["10","12","14","16"],1],
["Eng uzun daryo?",["Missisipi","Nil","Amazonka","Amudayo"],1],
["Orol dengizi qayerda joylashgan?",["Markaziy Osiyo","Yevropa","Afrika","Janubiy Amerika"],0],
["O'zbekistondagi eng katta ko'l?",["Orol","Aydarkul","Charvok","Issiqko'l"],1],
["Atmosfera nima?",["Havo qatlami","Suv qatlami","Tuproq qatlami","Tosh qatlami"],0],
["Litosfera nima?",["Yer po'sti","Havo","Suv","Biosfera"],0],
["Gidrosfera nima?",["Suv qobig'i","Havo","Yer po'sti","O'simliklar"],0],
["Yer qancha vaqtda o'z o'qi atrofida aylanadi?",["12 soat","24 soat","365 kun","30 kun"],1],
["Ekvator uzunligi taxminan?",["20000 km","40000 km","60000 km","10000 km"],1],
["Qaysi materik eng kichik?",["Yevropa","Avstraliya","Antarktida","Janubiy Amerika"],1],
["Iqlim zonalari nechta?",["5","7","9","11"],1],
["O'zbekiston qaysi iqlim mintaqasida?",["Tropik","Mo'tadil","Subtropik","Subarktik"],1],
["Cho'l iqlimining xususiyati?",["Quruq va issiq","Nam va sovuq","Mo'tadil","Yomg'irli"],0],
["Tuproq hosil bo'lish omillari?",["Iqlim, o'simlik, vaqt","Faqat suv","Faqat shamol","Faqat harorat"],0],
["Sirdaryo qayerga quyiladi?",["Orol dengiziga","Kaspiy dengiziga","Qora dengizga","Hind okeaniga"],0],
["O'zbekiston chegaradosh davlatlar soni?",["3","4","5","6"],2],
["Tog' iqlimining xususiyati?",["Balandlik bilan soviydi","Balandlik bilan isiydi","O'zgarmaydi","Faqat yomg'ir yog'adi"],0],
["Urbanizatsiya nima?",["Shaharlanish","Qishloqlanish","Cho'llanish","Sug'orish"],0],
["Demografiya nimani o'rganadi?",["Aholini","Iqlimni","Tuproquni","Suvni"],0],
["Seysmik zona nima?",["Zilzila xavfli hudud","Cho'l","Tog'","Tekislik"],0],
["O'zbekistonda qaysi foydali qazilma ko'p?",["Oltin","Olmos","Kumush","Platina"],0],
["Irrigatsiya nima?",["Sug'orish","Quritish","Ekin ekish","O'rm on kesish"],0],
["Subtropik iqlimda qaysi meva yetishtiriladi?",["Uzum","Olma","Kartoshka","Bug'doy"],0]
],
huquq:[
["O'zbekiston Konstitutsiyasi necha moddadan iborat?",["120","128","155","140"],2],
["Huquqiy davlat tamoyili nimani anglatadi?",["Qonun ustuvorligi","Prezident hokimiyati","Harbiy boshqaruv","Bir partiyali tizim"],0],
["Jinoyat huquqida jazoning maqsadi?",["Tuzatish va qayta tarbiyalash","Faqat jazo berish","Qamoqqa olish","Jarimaga tortish"],0],
["Fuqarolik huquqi nimani tartibga soladi?",["Mulkiy munosabatlar","Jinoyatlar","Soliqlar","Harbiy xizmat"],0],
["O'zbekistonda oliy sud organi?",["Oliy sud","Konstitutsion sud","Viloyat sudi","Tuman sudi"],0],
["Qonunchilik tashabbusi huquqi kimda?",["Prezident va deputatlar","Faqat Prezident","Faqat sudlar","Fuqarolar"],0],
["Mehnat shartnomasining minimal muddati?",["1 oy","Chegaralanmagan","1 yil","6 oy"],1],
["Bola huquqlari konvensiyasi qachon qabul qilingan?",["1979","1989","1999","2009"],1],
["Ma'muriy javobgarlik necha yoshdan?",["14","16","18","21"],1],
["Jinoyat javobgarligi umumiy tartibi necha yoshdan?",["14","16","18","21"],1],
["Prezident necha yil muddatga saylanadi?",["4","5","7","6"],2],
["Oliy Majlis nechta palatadan iborat?",["1","2","3","4"],1],
["Senat a'zolari soni?",["50","100","150","56"],1],
["Qonun qachon kuchga kiradi?",["Rasmiy e'lon qilinganidan so'ng","Qabul qilinganidan","Imzolanganidan","Yozilganidan"],0],
["Huquqbuzarlik turlari?",["Jinoyat, ma'muriy, intizomiy","Faqat jinoyat","Faqat ma'muriy","Faqat fuqarolik"],0],
["Advokat vazifasi?",["Huquqiy yordam ko'rsatish","Jazo tayinlash","Qonun qabul qilish","Tergov olib borish"],0],
["Notarius nimani tasdiqlaydi?",["Hujjatlarni","Jinoyatlarni","Qonunlarni","Sudlarni"],0],
["Prokuror vazifasi?",["Qonuniylik ustidan nazorat","Huquqiy yordam","Sud qarori","Shartnoma tuzish"],0],
["Inson huquqlari Deklaratsiyasi qachon qabul qilingan?",["1945","1948","1955","1960"],1],
["Referendumda kim qatnashadi?",["Barcha fuqarolar","Faqat deputatlar","Faqat Prezident","Faqat sudyalar"],0],
["Mulk huquqi nechta turga bo'linadi?",["2","3","4","5"],1],
["Meros huquqi qaysi huquq tarmog'iga kiradi?",["Fuqarolik","Jinoyat","Ma'muriy","Mehnat"],0],
["Nikoh yoshining minimal chegarasi?",["16","17","18","21"],2],
["Fuqarolikdan mahrum qilish mumkinmi?",["Yo'q","Ha","Faqat jinoyat uchun","Faqat xorijda"],0],
["Habeas corpus nima?",["Shaxs erkinligi kafolati","Mulk huquqi","Sud qarori","Qonun loyihasi"],0],
["Aybsizlik prezumpsiyasi nimani anglatadi?",["Aybsiz deb hisoblanish","Aybdor deb topish","Jazo tayinlash","Sudlov"],0],
["Ombudsman kim?",["Inson huquqlari bo'yicha vakil","Bosh prokuror","Bosh sudya","Bosh vazir"],0],
["O'zbekistonda sud tizimi necha bosqichli?",["2","3","4","5"],2],
["Deputatlik daxlsizligi nima?",["Immunitet","Jazo","Mukofot","Lavozim"],0],
["Fuqarolar qanday huquqlarga ega?",["Shaxsiy, siyosiy, iqtisodiy","Faqat siyosiy","Faqat iqtisodiy","Faqat shaxsiy"],0]
],
jahon_tarixi:[
["Ikkinchi Jahon urushi qachon boshlangan?",["1935","1939","1941","1945"],1],
["Fransuz inqilobi qachon bo'lgan?",["1776","1789","1799","1812"],1],
["Magna Carta qachon qabul qilingan?",["1066","1215","1300","1400"],1],
["Birinchi Jahon urushi qachon tugagan?",["1916","1917","1918","1919"],2],
["AQSH mustaqillik deklaratsiyasi qachon?",["1776","1783","1789","1800"],0],
["Rim imperiyasi qachon qulagan?",["376","410","476","500"],2],
["Kolumb Amerikani qachon kashf etgan?",["1453","1492","1500","1510"],1],
["Sanoat inqilobi qayerda boshlangan?",["Fransiya","Angliya","Germaniya","AQSH"],1],
["BMT qachon tashkil etilgan?",["1940","1945","1950","1955"],1],
["Xitoy Buyuk devori qachon qurilgan?",["Miloddan avval","Miloddan keyin 500","1000-yil","1500-yil"],0],
["Napoleonning Vaterloo jangi?",["1805","1812","1815","1820"],2],
["Sovet Ittifoqi qachon tarqalgan?",["1989","1990","1991","1992"],2],
["Berlin devori qachon qulatilgan?",["1987","1988","1989","1990"],2],
["Misrdagi piramidalar qachon qurilgan?",["Mil.avv. 2500","Mil.avv. 500","Milodiy 100","Milodiy 500"],0],
["Mongol imperiyasini kim asos solgan?",["Botir","Chingizxon","Oqtoy","Batu"],1],
["Renessans qayerda boshlangan?",["Fransiya","Ispaniya","Italiya","Angliya"],2],
["O'rta asrlar qaysi asrlarni o'z ichiga oladi?",["1-5","5-15","15-18","18-20"],1],
["Reformatsiya harakati asoschisi?",["Kalvin","Martin Lyuter","Genrix VIII","Papa"],1],
["Buyuk geografik kashfiyotlar qaysi asrda?",["13-14","15-16","17-18","19-20"],1],
["Xalqaro Qizil Xoch qachon tashkil etilgan?",["1850","1863","1870","1900"],1],
["Atom bombasi birinchi qayerda ishlatilgan?",["Germaniya","Yaponiya","Rossiya","Xitoy"],1],
["Versal shartnomasi qachon imzolangan?",["1918","1919","1920","1921"],1],
["Sovuq urush kimlar o'rtasida bo'lgan?",["AQSH-Xitoy","AQSH-SSSR","Angliya-Fransiya","Germaniya-AQSH"],1],
["Yevropa Ittifoqi qachon tashkil etilgan?",["1957","1975","1992","2000"],2],
["Hindiston mustaqilligi qachon?",["1945","1947","1950","1955"],1],
["Demokratiya qayerda paydo bo'lgan?",["Sparta","Afina","Korinfiya","Fiva"],1],
["Islom dini qaysi asrda paydo bo'lgan?",["5-asr","6-asr","7-asr","8-asr"],2],
["Birinchi yozuv qaysi sivilizatsiyada?",["Misr","Shumer","Xitoy","Hindiston"],1],
["Xristianlik qachon Rim davlat dini bo'lgan?",["313-yil","380-yil","476-yil","500-yil"],1],
["AQSHda qulchilik qachon bekor qilingan?",["1850","1863","1870","1900"],1]
],
ingliz_tili:[
["Choose the correct answer: I ___ to London several times this year.", ["have been", "was", "had been", "am going"], 0],
["Identify the correct passive voice: 'They are building a new hospital.'", ["A new hospital is built.", "A new hospital is being built.", "A new hospital was being built.", "A new hospital has been built."], 1],
["Complete the conditional sentence: If I ___ you, I would study harder.", ["am", "was", "were", "had been"], 2],
["Choose the correct preposition: She is very good ___ learning languages.", ["in", "at", "on", "about"], 1],
["What is the synonym of 'crucial'?", ["Unimportant", "Optional", "Essential", "Minor"], 2],
["Choose the correct reported speech: 'I am reading a book,' he said.", ["He said that he is reading a book.", "He said that he was reading a book.", "He said me he was reading a book.", "He says he read a book."], 1],
["Fill in the blank: By the time we arrived, the train ___.", ["left", "has left", "had left", "was leaving"], 2],
["Find the error: Neither of the students have finished their homework.", ["Neither", "of the", "have", "their"], 2],
["Choose the correct article: He is ___ honest man.", ["a", "an", "the", "no article"], 1],
["Which word means 'to put off until another time'?", ["Procrastinate", "Accelerate", "Determine", "Evaluate"], 0],
["Choose the correct modal verb: You ___ smoke in a hospital.", ["mustn't", "don't have to", "needn't", "shouldn't"], 0],
["Complete the sentence: Despite ___ tired, he continued to work.", ["he was", "being", "of being", "was"], 1],
["What is the antonym of 'abundant'?", ["Plentiful", "Scarce", "Rich", "Ample"], 1],
["Choose the correct relative pronoun: The man ___ car was stolen reported it to the police.", ["who", "whom", "whose", "which"], 2],
["Identify the tense: 'She has been studying for three hours.'", ["Present Perfect", "Present Perfect Continuous", "Past Perfect Continuous", "Present Continuous"], 1],
["Fill in the blank: I'm looking forward to ___ you.", ["see", "seeing", "saw", "be seen"], 1],
["Choose the correct form: It's high time we ___ home.", ["go", "went", "are going", "will go"], 1],
["What is the meaning of the idiom 'to hit the nail on the head'?", ["To make a mistake", "To be exactly right", "To hurt oneself", "To build something"], 1],
["Choose the right connector: ___ it was raining, we went for a walk.", ["Although", "Because", "However", "Therefore"], 0],
["Fill in: She is the best singer ___ I have ever heard.", ["who", "which", "that", "whom"], 2],
["Choose the correct inversion: Seldom ___ such a beautiful sunset.", ["I have seen", "have I seen", "did I saw", "I saw"], 1],
["Identify the correct spelling.", ["Accommodate", "Acommodate", "Accomodate", "Acomodate"], 0],
["Choose the correct quantifier: There is ___ milk left in the fridge.", ["few", "a few", "little", "many"], 2],
["Fill in: I would rather you ___ it now.", ["do", "did", "have done", "will do"], 1],
["What is the prefix of 'understand'?", ["mis-", "un-", "in-", "dis-"], 0],
["Choose the correct question tag: Let's go to the cinema, ___?", ["shall we", "will we", "don't we", "aren't we"], 0],
["Fill in: The harder you work, ___ you will become.", ["the most successful", "the more successful", "more successful", "most successful"], 1],
["Choose the right word: Can you give me a ___ of advice?", ["piece", "slice", "block", "drop"], 0],
["Identify the gerund: 'Running is good for your health.'", ["Running", "is", "good", "health"], 0],
["Choose the correct preposition: We congratulated him ___ his success.", ["for", "on", "with", "about"], 1]
]
};